config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'youtube/index'
  get 'youtube/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: :index

  resources :users, only: %i[index show]
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  resources :posts, only: %i[new index show create edit update destroy] do
    resources :comments, only: %i[create update edit destroy update]
    resources :likes, only: %i[create destroy]
  end

  get 'search' => 'posts#search' # 記事検索機能

  resources :users do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 8 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :omniauthable, omniauth_providers: [:google_oauth2]
  mount_uploader :image, ImageUploader
  validates :profile, length: { maximum: 200 }
  has_many :sns_credentials, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_posts, through: :likes, source: :post # いいね機能の利用
  has_many :following_relationships, class_name: 'Relationship', foreign_key: 'follower_id', dependent: :destroy # フォローできるユーザーを取り出す
  has_many :followings, through: :following_relationships # フォローしているユーザーを取り出す
  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'following_id', dependent: :destroy # フォローされているユーザーを取り出す
  has_many :followers, through: :follower_relationships # フォローされているユーザーを取り出す

  has_many :active_notifications, class_name: 'Notification', foreign_key: 'visitor_id', dependent: :destroy
  has_many :passive_notifications, class_name: 'Notification', foreign_key: 'visited_id', dependent: :destroy

  # フォロー通知
  def create_notification_follow!(current_user)
    temp = Notification.where(['visitor_id = ? and visited_id = ? and action = ? ', current_user.id, id, 'follow'])
    if temp.blank?
      notification = current_user.active_notifications.new(
        visited_id: id,
        action: 'follow'
      )
      notification.save if notification.valid?
    end
  end

  # いいねしているかどうか
  def already_liked?(post)
    likes.exists?(post_id: post.id)
  end

  # フォローしているか調べる
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  # フォローする
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  # フォローを外す
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  def active_for_authentication?
    super && (is_deleted == false)
  end

  def self.without_sns_data(auth)
    user = User.where(email: auth.info.email).first

    if user.present?
      sns = SnsCredential.create(
        uid: auth.uid,
        provider: auth.provider,
        user_id: user.id
      )
    else
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
      sns = SnsCredential.new(
        uid: auth.uid,
        provider: auth.provider
      )
    end
    { user: user, sns: sns }
  end

  def self.with_sns_data(auth, snscredential)
    user = User.where(id: snscredential.user_id).first
    unless user.present?
      user = User.new(
        name: auth.info.name,
        email: auth.info.email
      )
    end
    { user: user }
  end

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = with_sns_data(auth, snscredential)[:user]
      sns = snscredential
    else
      user = without_sns_data(auth)[:user]
      sns = without_sns_data(auth)[:sns]
    end
    { user: user, sns: sns }
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end

  def google_oauth2
    callback_for(:google)
  end

  def callback_for(provider)
    @omniauth = request.env['omniauth.auth']
    info = User.find_oauth(@omniauth)
    @user = info[:user]
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: provider.to_s.capitalize) if is_navigational_format?
    else
      @sns = info[:sns]
      render template: 'devise/registrations/new'
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    # super
    # /users/sign_up(.:format)でわざとエラーを出す。
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # 更新（編集の反映）時にパスワード入力を省く
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # 更新後のパスを指定
  def after_update_path_for(_resource)
    user_path(@user.id)
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.page(params[:page]).order(created_at: :desc).per(4)
  end

  def show
    @user = User.find(params[:id])
    @users = @user.posts.page(params[:page]).order(created_at: :desc).per(1)
    @user_counts = @user.liked_posts.includes(:user).count
    @user_favorites = @user.liked_posts.includes(:taggings, :user).order('RANDOM()').limit(2)
  end

  # フォロー関連
  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  def hide
    @user = User.find(params[:id]) # ユーザ毎の情報を得る
    @user.destroy # ユーザ情報を削除（退会）
    flash[:notice] = 'ありがとうございました。またのご利用を心よりお待ちしております。'
    redirect_to root_path
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(user)
    user == current_user
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: relationships_path, method: :post, remote: true) do |f| %>
<%= hidden_field_tag :following_id, @user.id %>
<%= f.submit "フォロー", class: "btn btn-large btn-primary follow-btn" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
  <% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
  <% else %>
  <%= render 'follow' %>
  <% end %>
</div>

<div id="stats">
  <% if current_user.following?(@user) %>
  <%= render 'stats' %>
  <% else %>
  <%= render 'stats' %>
  <% end %>
</div>
<% end %>

app/views/users/_stats.html.erb
 <% @user ||= current_user %>
 <div class="stats">
   <a href="<%= following_user_path(@user) %>">
     <strong id="following" class="stat">
       <%= @user.followings.count %>
     </strong>
     フォロー中
   </a>
   <a href="<%= followers_user_path(@user) %>">
     <strong id="followers" class="stat">
       <%= @user.followers.count %>
     </strong>
     フォロワー
   </a>
 </div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: relationship_path(@user), method: :delete, remote: true) do |f| %>
<%= f.submit "フォロー中", class: "btn btn-large follow-btn btn-outline-dark" %>
<% end %>

app/views/users/index.html.erb
<%= render "shared/link_home" %>
<hr class="border_none">
<div class="center-letter">
  <h4><i class="fas fa-users"></i> ユーザー一覧</h4>
</div>
<hr>
<div class="skill-list jscroll">
<% @users.each do |user| %>
<img src=<%= user.image %> class="icon_image">
<%= link_to "#{user.name}", "/users/#{user.id}" %>
<%= link_to "#{user.posts.count}件の投稿があります。", "/users/#{user.id}", :style => "color: black;" %>
<hr>
<% end %>

<%= paginate @users %>
</div>
<hr class="border_none">
<%= render "shared/link_home" %>

app/views/users/show.html.erb
<%= render "shared/link_home" %>
<hr class="border_none">
<div class="center-letter">
    <% if user_signed_in? && @user.id == current_user.id %>
    <h4><i class="fa fa-user-plus"></i> マイページ</h4>
    <% else %>
    <h4><i class="fa fa-user-plus"></i> ユーザー詳細</h4>
    <% end %>
</div>
<hr>
<% if @user.image.blank? %>
<%= image_tag '/default.png', class: "icon_image_large" %>
<% else %>
<img src=<%= @user.image %> class="icon_image_large">
<% end %>
<% if user_signed_in? && @user.id == current_user.id %>
<%= render 'users/stats' %>
<% end %>

<%# フォロー関連 %>
<div class="margin_up_down">
    <%= render 'follow_form' %>
</div>

<h5 class="margin_up_up">ユーザー名</h5>
<%= @user.name %>
<h5 class="margin_up_up">メールアドレス</h5>
<%= @user.email %>
<h5 class="margin_up_up">プロフィール</h5>
<%= simple_format(@user.profile) %>

<% if user_signed_in? && @user.id == current_user.id %>
<p><%= link_to edit_user_registration_path do %>ユーザー情報を編集する <i class="fas fa-edit"></i><% end %></p>
<% elsif current_user.id == 2 %>
<p class="margin_up">
    <%= link_to "強制退会させる", users_hide_path(params[:id]), method: :put, "data-confirm" => "本当に強制退会しますか？", class: "btn btn-outline-danger" %>
</p>
<% end %>

<hr>
<div class="center-letter">
    <h4><i class="fas fa-heart"></i> いいねしている投稿</h4>
</div>
<% if @user.liked_posts.exists? %>
<%= @user_counts %>件の投稿をいいねしています。
<% else %>
<center>
    いいねをしている投稿がありません
</center>
<% end %>
<% if @user_counts >= 3 %>
<span class="badge">ランダムで2件まで表示</span>
<% end %>
<% @user_favorites.each do |post| %>
<div class="row no-gutters bg-white position-relative box">
    <%= render partial: "posts/index", locals: { post: post } %>
</div>
<p>
    <% end %>

    <hr>
    <div class="center-letter">
        <h4><i class="fas fa-clipboard"></i> 投稿内容</h4>
    </div>
    <% if @users.exists? %>
    <div class="skill-list jscroll">

        <% @users.each do |post| %>
        <div id="parent_flame" class="row no-gutters bg-white position-relative box">
            <%= render partial: "posts/index", locals: { post: post } %>
        </div>
        <p>
            <% end %>
            <%= paginate @users %>
    </div>
    <% else %>
    <center>
        投稿はありません
    </center>
    <% end %>
    <hr>
    <hr class="border_none">
    <%= render "shared/link_home" %>

app/views/users/show_follow.html.erb
 <%= render "shared/link_home" %>
<hr class="border_none">
 <% @user ||= current_user %>
 <div class="stats">
   <a href="<%= following_user_path(@user) %>">
     <strong id="following" class="stat">
       <%= @user.followings.count %>
     </strong>
     フォロー中
   </a>
 </div>
 <hr>
 <% @user.followings.each do |user| %>
 <div>
   <% if user.image.blank? %>
   <%= link_to "/users/#{user.id}" do %>
   <%= image_tag '/default.png', class: "icon_image" %><%= link_to "#{user.name}", "/users/#{user.id}", :style => "color: black;" %>
   <% end %>
   <% else %>
   <%= link_to "/users/#{user.id}" do %>
   <img src=<%= user.image %>
     class="icon_image"><%= link_to "#{user.name}", "/users/#{user.id}", :style => "color: black;" %>
   <% end %>
   <% end %>
   <%= link_to '詳細', user_path(user) %>
 </div>
 <hr>
 <% end %>
 <hr class="border_none">
 <%= render "shared/link_home" %>

app/views/users/show_follower.html.erb
<%= render "shared/link_home" %>
<hr class="border_none">
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    フォロワー
  </a>
</div>
<hr>
<% @user.followers.each do |user| %>
<div>
  <% if user.image.blank? %>
  <%= link_to "/users/#{user.id}" do %>
  <%= image_tag '/default.png', class: "icon_image" %><%= link_to "#{user.name}", "/users/#{user.id}", :style => "color: black;" %>
  <% end %>
  <% else %>
  <%= link_to "/users/#{user.id}" do %>
  <img src=<%= user.image %>
    class="icon_image"><%= link_to "#{user.name}", "/users/#{user.id}", :style => "color: black;" %>
  <% end %>
  <% end %>
  <%= link_to '詳細', user_path(user) %>
</div>
<hr>
<% end %>
<hr class="border_none">
<%= render "shared/link_home" %>