config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'youtube/index'
  get 'youtube/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: :index

  resources :users, only: %i[index show]
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  resources :posts, only: %i[new index show create edit update destroy] do
    resources :comments, only: %i[create update edit destroy update]
    resources :likes, only: %i[create destroy]
  end

  get 'search' => 'posts#search' # 記事検索機能

  resources :users do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/views/shared/_categories_etc.html.erb
<hr>
<% @categories.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-primary" do %>
<i class="fas fa-tag"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>

<hr>
<% @occupations.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-success" do %>
<i class="fas fa-tags"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>

<hr>
<% @targets.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-danger" do %>
<i class="fas fa-user-tag"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>

app/views/shared/_circle.html.erb
<%= link_to(notifications_path) do %>
  <% if unchecked_notifications.any? %>
    <span class="fa-stack">
      <i class="far fa-bell fa-lg faa-ring animated" style="font-size: 1.7em;"></i>
      <i class="fas fa-circle n-circle fa-stack-1x"></i>
    </span>
  <% else %>
    <i class="far fa-bell fa-lg" style="font-size: 1.7em;"></i>
  <% end %> 
<% end %>

app/views/shared/_inquiry.html.erb
<li class="nav-item underscore">
  <a class="js-modal-open nav-link" href=""><i class="fas fa-envelope"></i> お問い合わせ</a>
  <% if user_signed_in? %>
  </div>
  <% else %>
  </li>
  <% end %>
  <div class="modal js-modal">
    <div class="modal__bg js-modal-close"></div>
    <div class="modal__content">

      <%= render "inquiry/index" %>

      <a class="js-modal-close" href="">閉じる</a>
    </div>
    <!--modal__inner-->
  </div>
  <!--modal-->
  </div>

app/views/shared/_link_back.html.erb
<div class="margin_up">
    <%= link_to(:back, class: "btn btn-light") do %>
    <i class="fas fa-step-backward"></i> 元のページへ戻る
    <% end %>
</div>

app/views/shared/_link_home.html.erb
<div class="margin_up">
    <%= link_to(posts_path, class: "btn btn-light") do %>
    <i class="fas fa-step-backward"></i> 投稿一覧へ戻る
    <% end %>
</div>

app/views/shared/_profile.html.erb
<div class="badge">ようこそ</div>
<% if user_signed_in? %>
<% if current_user.image.blank? %>
<%= link_to "/users/#{current_user.id}" do %>
<%= image_tag '/default.png', class: "icon_image" %>
<% end %>
<% else %>
<%= link_to "/users/#{current_user.id}" do %>
<img src=<%= current_user.image %> class="icon_image">
<% end %>
<% end %>
<li class="underscore edge">
  <%= link_to("#{current_user.name}", user_path(current_user.id)) %>
  <div class="badge">さん</div>
</li>
<% else %>
ゲストユーザー
<div class="badge">さん</div>
<div class="small">
※現在一部の機能のみご利用頂けます
</div>
<hr>
<% end %>