config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'youtube/index'
  get 'youtube/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: :index

  resources :users, only: %i[index show]
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  resources :posts, only: %i[new index show create edit update destroy] do
    resources :comments, only: %i[create update edit destroy update]
    resources :likes, only: %i[create destroy]
  end

  get 'search' => 'posts#search' # 記事検索機能

  resources :users do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/models/post.rb
class Post < ApplicationRecord
  acts_as_taggable_on :categories, :occupations, :targets
  # acts_as_taggable

  validates :title, { presence: true, length: { maximum: 100 } } # 未入力NG, 最大文字数制限あり
  VALID_YOUTUBE_URL = %r{(\Ahttps://www\.youtube\.com/watch\?v=)+\w{11}}
  validates :url, { presence: true, format: { with: VALID_YOUTUBE_URL }, length: { maximum: 120 } } # 未入力NG, YouTubeのURL以外NG, 最大文字数を120文字
  validates :content, { presence: true, length: { maximum: 300 } } # 未入力NG, 最大文字数を300文字
  validates :category_list, { presence: true }
  validates :occupation_list, { presence: true }
  validates :target_list, { presence: true }

  belongs_to :user
  has_many :comments, dependent: :destroy # 追加 コメント 削除も仮追加
  has_many :likes, dependent: :destroy # 追加 もしpostがデータベースから削除されてしまった場合、likesも削除
  has_many :liked_users, through: :likes, source: :user # 追加 いいね機能の利用

  has_many :notifications, dependent: :destroy # いいねの通知

  # 記事検索
  def self.search(search)
    joins(:user).where(['title LIKE ? OR content LIKE ? OR users.name LIKE ?', "%#{search}%", "%#{search}%",
                        "%#{search}%"])
  end

  # いいね通知
  def create_notification_like!(current_user)
    # すでに「いいね」されているか検索
    temp = Notification.where(['visitor_id = ? and visited_id = ? and post_id = ? and action = ? ', current_user.id,
                               user_id, id, 'like'])
    # いいねされていない場合のみ、通知レコードを作成
    if temp.blank?
      notification = current_user.active_notifications.new(
        post_id: id,
        visited_id: user_id,
        action: 'like'
      )
      # 自分の投稿に対するいいねの場合は、通知済みとする
      notification.checked = true if notification.visitor_id == notification.visited_id
      notification.save if notification.valid?
    end
  end

  # コメント通知
  def create_notification_comment!(current_user, comment_id)
    # 自分以外にコメントしている人をすべて取得し、全員に通知を送る
    temp_ids = Comment.select(:user_id).where(post_id: id).where.not(user_id: current_user.id).distinct
    save_notification_comment!(current_user, comment_id, user_id) # 投稿者への通知
    temp_ids.each do |temp_id|
      save_notification_comment!(current_user, comment_id, temp_id['user_id'])
    end
  end

  def save_notification_comment!(current_user, comment_id, visited_id)
    # コメントは複数回することが考えられるため、１つの投稿に複数回通知する
    notification = current_user.active_notifications.new(
      post_id: id,
      comment_id: comment_id,
      visited_id: visited_id,
      action: 'comment'
    )
    # 自分の投稿に対するコメントの場合は、通知済みとする
    notification.checked = true if notification.visitor_id == notification.visited_id
    notification.save if notification.valid?
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[index search create new create edit update destroy]

  def index
    @posts = Post.includes(:taggings, :user).page(params[:page]).per(1).order(created_at: :desc)
    if params[:tag_name]
      @posts = Post.includes(:taggings,
                             :user).tagged_with(params[:tag_name].to_s).page(params[:page]).per(1).order(created_at: :desc)
    end
  end

  # 記事検索
  def search
    # Viewのformで取得したパラメータをモデルに渡す
    @posts_count = Post.search(params[:search]).count
    @posts = Post.includes(:taggings, :user).search(params[:search]).page(params[:page]).per(1).order(created_at: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @new_posts = Time.now.at_beginning_of_day - 168.hour
    @comment = Comment.new
    @comments = @post.comments.includes(:user)
    @like = Like.new # いいね機能
  end

  # 新規投稿
  def new
    @post = Post.new
    @tags = ActsAsTaggableOn::Tag.all
  end

  # 新規投稿→投稿送信
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = '投稿を作成しました。'
      # redirect_to("/posts")
      redirect_to @post
    else
      flash.now[:alert] = '投稿に失敗しました。'
      @tags = ActsAsTaggableOn::Tag.all
      render('/posts/new')
    end
  end

  # 投稿編集
  def edit
    @post = Post.find_by(id: params[:id])
  end

  # 投稿編集→投稿更新
  def update
    @post = Post.find_by(id: params[:id])
    if @post.update(post_params)
      flash[:notice] = '投稿を編集しました。'
      redirect_to @post
    else
      render :new
    end
  end

  # 投稿編集→投稿削除
  def destroy
    @post = Post.find_by(id: params[:id])
    @post.destroy
    flash[:notice] = '投稿を削除しました。'
    redirect_to('/posts')
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, category_list: [], occupation_list: [], target_list: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_category_list.html.erb
カテゴリー：
<% category_list.each do |tag| %>
<%= link_to posts_path(tag_name: tag), class: "badge badge-pill badge-primary" do %>
<i class="fas fa-tag"></i><%= tag %>
<% end %>
<% end %>

app/views/posts/_edit.html.erb
<%= form_for(@post, url: post_path(@post)) do |f| %>
<div><%= f.label :title, "タイトル：", class: "font-weight-bold field" %></div>
<% @post.errors.full_messages_for(:title).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div>
  <%= f.text_field :title, placeholder: "23文字以内推奨", class: "url_text", id: "post_title" %>
</div>
<div><%= f.label :url, "紹介したいYouTubeのURL：", class: "font-weight-bold field" %></div>
<% @post.errors.full_messages_for(:url).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<diV>
  <%= f.text_field :url, placeholder: "https://www.youtube.com/watch?v=", class: "url_text", id: "post_url" %>
</div>
<div class="badge">※一部外部サイトへの転載NGの動画もあります。</div>
<div class="font-weight-bold field">カテゴリー：</div>
<% @post.errors.full_messages_for(:category_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @categories.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :category_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-primary" %></span>&emsp;
  <% end %>
</div>
<div class="font-weight-bold field">対象職種：</div>
<% @post.errors.full_messages_for(:occupation_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @occupations.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :occupation_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-success" %></span>&emsp;
  <% end %>
</div>
<div class="font-weight-bold field">対象者：</div>
<% @post.errors.full_messages_for(:target_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @targets.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :target_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-danger" %></span>&emsp;
  <% end %>
</div>
<div><%= f.label :content, "紹介文：", class: "font-weight-bold field" %></div>
<% @post.errors.full_messages_for(:content).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<diV>
  <%= f.text_area :content, placeholder: "300文字内で入力", class: "textarea", id: "post_content" %>
</div>

<div><%= f.submit "更新する", class: 'btn btn-primary' %></div>
<% end %>

app/views/posts/_index.html.erb
<div class="col-md-6 mb-md-0 p-md-4">
    <div class="max-youtube">
        <div class="responsibe-youtube">
            <iframe width="560" height="315" src="<%= "https://www.youtube.com/embed/#{post.url[32..42]}" %>?rel=0"
                frameborder="0"
                allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        </div>
    </div>
</div>
<div class="col-md-6 position-static p-4 pl-md-0">
    <span
        class="posted-date"><%= link_to(post.created_at.strftime("%Y-%m-%d %H:%M:%S"), "/posts/#{post.id}", class: "cp_link") %></span>
    <% if not post.created_at <= (Time.now.at_beginning_of_day - 168.hour) %>
    <div class="badge badge-secondary balloonoya">New
        <span class="balloon"><%= time_ago_in_words(post.created_at) %>前の投稿</span>
    </div>
    <% end %>
    <div>
        <%= render 'posts/category_list', category_list: post.category_list %>
    </div>
    <div>
        <%= render 'posts/occupation_list', occupation_list: post.occupation_list %>
    </div>
    <div>
        <%= render 'posts/target_list', target_list: post.target_list %>
    </div>

    <div class="box26">
        <span class="box-title cp_link_b"><%= link_to(post.title.truncate(26, omission: '...'), "/posts/#{post.id}") %></span>

        <p><%= link_to(post.content.truncate(40, omission: '...(続きを読む)'), "/posts/#{post.id}", class: "cp_link_b") %>
        </p>
    </div>

    <div id="child_flame_br">
        <% if post.user.image.blank? %>
        投稿者：<%= link_to "/users/#{post.user.id}" do %>
        <%= image_tag '/default.png', class: "icon_image" %>
        <% end %>
        <%= link_to "#{post.user.name}", "/users/#{post.user.id}" %>
        <% else %>
        投稿者：<%= link_to "/users/#{post.user.id}" do %>
        <img src=<%= post.user.image %> class="icon_image">
        <% end %>
        <%= link_to "#{post.user.name}", "/users/#{post.user.id}" %>
        <% end %>

        コメント：<%= post.comments.count %>件

        <% if not post.liked_users.count == 0 %>
        <i class="fas fa-heart unlike-btn" style="color: #e54747;"></i><span
            style="color: #e54747;"><%= post.likes.count %></span>
        <% else %>
        <i class="far fa-heart like-btn" style="color: #808080;"></i><span
            style="color: #808080;"><%= post.likes.count %></span>
        <% end %>
    </div>
</div>

app/views/posts/_occupation_list.html.erb
対象職種：
<% occupation_list.each do |tag| %>
<%= link_to posts_path(tag_name: tag), class: "badge badge-pill badge-success" do %>
<i class="fas fa-tags"></i><%= tag %>
<% end %>
<% end %>

app/views/posts/_post.html.erb
<%= form_for @post do |f| %>
<div><%= f.label :title, "タイトル：", class: "font-weight-bold field" %></div>
<% @post.errors.full_messages_for(:title).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div>
  <%= f.text_field :title, placeholder: "23文字以内推奨", class: "url_text", id: "post_title" %>
</div>
<div class="youtube_show"><%= f.label :url, "紹介したいYouTubeのURL：", class: "font-weight-bold field" %><div class="badge"><i class="fas fa-chevron-circle-down"></i> 動画を探してみる <i class="fas fa-chevron-circle-down"></i></div></div>
<div class="p-faq-description">
<li><%= link_to("本サイトIllustTubeから", youtube_search_path(keyword: "キャラクター 上達"), target: :_blank) %></li>
<li><%= link_to("YouTube公式サイトから", "https://www.youtube.com/results?search_query=キャラクター 上達", target: :_blank) %></li>
</div>
<% @post.errors.full_messages_for(:url).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<diV>
  <%= f.text_field :url, placeholder: "https://www.youtube.com/watch?v=", class: "url_text", id: "post_url" %>
</div>
<div class="badge">※一部外部サイトへの転載NGの動画もあります。</div>
<div class="font-weight-bold field">カテゴリー：</div>
<% @post.errors.full_messages_for(:category_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @categories.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :category_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-primary" %></span>&emsp;
  <% end %>
</div>
<div class="font-weight-bold field">対象職種：</div>
<% @post.errors.full_messages_for(:occupation_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @occupations.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :occupation_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-success" %></span>&emsp;
  <% end %>
</div>
<div class="font-weight-bold field">対象者：</div>
<% @post.errors.full_messages_for(:target_list).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<div class="col-sm-12">
  <% @targets.each do |tag| %>
  <span class="check_paragraph"><%= f.check_box :target_list, { multiple: true }, "#{tag.name}", nil %>
    <%= f.label "#{tag.name}(#{tag.taggings_count})", class: "badge badge-danger" %></span>&emsp;
  <% end %>
</div>
<div><%= f.label :content, "紹介文：", class: "font-weight-bold field" %></div>
<% @post.errors.full_messages_for(:content).each do |message| %>
<div class="badge badge-warning">
  <%= message %>
</div>
<% end %>
<diV>
  <%= f.text_area :content, placeholder: "300文字内で入力", class: "textarea", id: "post_content" %>
</div>
<%= f.submit '投稿する', class: 'btn btn-primary' %>
<% end %>

app/views/posts/_postcopy.html.erb
<h2>投稿する</h2>
  <%= form_for @post do |f| %>
    <%# <%= f.label :content %>
    <% @post.errors.full_messages_for(:title).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
    <diV>
    <%= f.text_field :title, placeholder: "タイトル" %>
    </div>
    <p>

    <% @post.errors.full_messages_for(:url).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
    <diV>
    <%= f.text_field :url, placeholder: "YouTubeのURLを入力して下さい" %>
    </div>
    <p>

    <% @post.errors.full_messages_for(:content).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
    <diV>
    <%= f.text_area :content, placeholder: "紹介文" %>
    </div>
    <%= f.submit %>
  <% end %>

app/views/posts/_tag .html.erb
<hr>
<% @categories.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-primary" do %>
<i class="fas fa-tag"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>
<hr>
<% @occupations.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-success" do %>
<i class="fas fa-tags"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>
<hr>
<% @targets.each do |tag| %>
<%= link_to posts_path(tag_name: tag.name), class: "badge badge-pill badge-danger" do %>
<i class="fas fa-user-tag"></i><%= tag.name %>(<%= tag.taggings_count %>)
<% end %>
<% end %>

app/views/posts/_target_list.html.erb
対象者：
<% target_list.each do |tag| %>
<%= link_to posts_path(tag_name: tag), class: "badge badge-pill badge-danger" do %>
<i class="fas fa-user-tag"></i><%= tag %>
<% end %>
<% end %>

app/views/posts/edit.html.erb
<h4><i class="fas fa-clipboard"></i> 編集</h4>
<%= render "edit" %>

app/views/posts/index.html.erb
<% if user_signed_in? %>
<div class="center-letter">
    <h4><i class="fas fa-film"></i> 投稿一覧</h4>
</div>
<% if params[:tag_name] %>
<h5><%= params[:tag_name] %></h5>
<% end %>
<% if @posts.exists? %>
<div class="skill-list jscroll">
    <% @posts.each do |post| %>
    <div id="parent_flame" class="row no-gutters bg-white position-relative box">
        <%= render partial: "index", collection: @posts, as: 'post' %>
    </div>
    <p>
        <% end %>
        <%= paginate @posts %>
</div>
<% else %>
<center>
<hr>
投稿はありません
<hr>
</center>
<% end %>
<% end %>

app/views/posts/new.html.erb
<h4><i class="fas fa-clipboard"></i> 新規投稿</h4>
<%= render "posts/post" %>

app/views/posts/search.html.erb
<%= render "shared/link_home" %>
<hr class="border_none">
<div class="center-letter">
    <h4><i class="fa fa-search"></i> 検索結果</h4>
</div>
<%= form_tag(search_path, method: 'get', id: "search_form_pc_sp") do %>
<%= text_field_tag :search, '',value: params[:search], placeholder: "投稿記事を探す", class: 'search_text_pc_sp search_yt_text' %>
<%= button_tag :name => nil, class: "btn-outline-info badge-light search_right_text" do %>
<i class="fa fa-search"></i>
<% end %>
<% end %>
<% if @posts_count == 0 %>
<div class="small">「<%= params[:search] %>」のキーワードでの投稿はありません。</div>
<div class="small"><%= current_user.name %>さんが投稿者になって皆様の学習をサポートしてみませんか？</div>
<% else %>
<div class="small">「<%= params[:search] %>」のキーワードで<%= @posts_count %>件の記事が投稿されています。</div>
<div class="skill-list jscroll">
    <% @posts.each do |post| %>
    <div id="parent_flame" class="row no-gutters bg-white position-relative box">
        <%= render partial: "index", collection: @posts, as: 'post' %>
    </div>
    <p>
        <% end %>
        <%= paginate @posts %>
</div>
<div class="small">ご希望のYouTube動画は見つかりましたか？</div>
<div class="small">もし見つからない場合、<%= current_user.name %>さんが投稿者になって皆様の学習をサポートしてみませんか？</div>
<% end %>
<p>
<%= link_to youtube_search_path(keyword: "イラスト 描き方"), method: :get do %>
<i class="fab fa-youtube faa-flash animated"></i> 新規投稿してみる
<% end %>
<div class="center-letter">
<hr class="border_none">
<%= render "shared/link_home" %>

app/views/posts/show.html.erb
<%= render "/shared/link_home" %>
<hr class="border_none">
<h4><%= @post.title %></h4>
<div><span class="posted-date"><%= @post.created_at.strftime("%Y-%m-%d %H:%M:%S") %></span>
  <% if not @post.created_at <= (@new_posts) %>
  <div class="badge badge-secondary balloonoya">New
    <span class="balloon"><%= time_ago_in_words(@post.created_at) %>前の投稿</span>
  </div>
  <% end %>

  <div class="post_show">
    <div>
      <%= render 'posts/category_list', category_list: @post.category_list %>
    </div>
    <div>
      <%= render 'posts/occupation_list', occupation_list: @post.occupation_list %>
    </div>
    <div>
      <%= render 'posts/target_list', target_list: @post.target_list %>
    </div>

    <hr class="border_none">
    <div class="max-youtube">
      <div class="responsibe-youtube">
        <iframe width="560" height="315" src="<%= "https://www.youtube.com/embed/#{@post.url[32..42]}" %>?rel=0"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
    </div>

    <hr class="border_none">
    <p class="textarea_post"><%= @post.content %></p>

    <hr>
    <% if @post.user.image.blank? %>
    <div>
      投稿者：
      <%= link_to "/users/#{@post.user.id}" do %>
      <%= image_tag '/default.png', class: "icon_image" %><%= link_to "#{@post.user.name}", "/users/#{@post.user.id}" %>
      <% end %>
    </div>
    <% else %>
    <div>投稿者：
      <%= link_to "/users/#{@post.user.id}" do %>
      <img src=<%= @post.user.image %> class="icon_image">
      <% end %>
      <%= link_to "#{@post.user.name}", "/users/#{@post.user.id}" %></div>
    <% end %>

<% if user_signed_in? %>
    <% if current_user.id == @post.user_id %>
    <div>
      <%= link_to "/posts/#{@post.id}", method: "delete", data: { confirm: "本当に削除しますか?"} do %>削除 <i
        class="fas fa-trash"></i><% end %>
      <%= link_to("/posts/#{@post.id}/edit") do %>編集 <i class="fas fa-edit"></i><% end %>
    </div>
    <% elsif current_user.id == 2 %>
    <div>
      <%= link_to "/posts/#{@post.id}", method: "delete", data: { confirm: "本当に削除しますか?"} do %>管理者権限で削除 <i
        class="fas fa-trash"></i><% end %>
      <%= link_to("/posts/#{@post.id}/edit") do %>管理者権限で編集 <i class="fas fa-edit"></i><% end %>
    </div>
    <% end %>
<% end %>

    <%= link_to "https://twitter.com/share?url=#{request.url}/&text=#{ @post.title } - IllustTube", title: 'Twitter', target: '_blank' do %>
    <i class="fab fa-twitter fa-2x"></i>
    <% end %>

    <%= link_to "http://line.me/R/msg/text/?#{ @post.title } - IllustTube #{request.url}", title: 'Line', target: '_blank' do %>
    <i class="fab fa-line fa-2x" style="color:#00B900;"></i>
    <% end %>
  </div>

  <div class="like">
    <%= render partial: "likes/like", locals: {post: @post} %>
  </div>

  <% if user_signed_in? %>
  <hr>
  <h5>コメントを投稿する</h5>
  <%= render partial: 'comments/form', locals: { comment: @comment, post: @post } %>
  <% end %>

  <div id="error_explanation">
  </div>

  <hr>
  <h5>コメント一覧</h5>
  <div id="comments_area">
    <%= render partial: 'comments/index', locals: { comments: @comments, post: @post } %>
  </div>
  <hr class="border_none">
  <%= render "/shared/link_home" %>