config/routes.rb
Rails.application.routes.draw do
  get 'inquiry/index'
  get 'inquiry/confirm'
  get 'inquiry/thanks'
  get 'youtube/index'
  get 'youtube/search'

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  resources :relationships, only: %i[create destroy]
  resources :notifications, only: :index

  resources :users, only: %i[index show]
  put '/users/:id/hide' => 'users#hide', as: 'users_hide'
  resources :posts, only: %i[new index show create edit update destroy] do
    resources :comments, only: %i[create update edit destroy update]
    resources :likes, only: %i[create destroy]
  end

  get 'search' => 'posts#search' # 記事検索機能

  resources :users do
    member do
      get :following, :followers
    end
  end

  devise_scope :user do
    root to: 'devise/registrations#new'
  end

  get   'inquiry'         => 'inquiry#index'     # 入力画面
  post  'inquiry/confirm' => 'inquiry#confirm'   # 確認画面
  post  'inquiry/thanks'  => 'inquiry#thanks'    # 送信完了画面
end

app/views/layouts/_alert.html.erb
<% if notice %>
<div class="alert alert-info"><%= notice %>
  <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>
<% elsif alert %>
<div class="alert alert-danger"><%= alert %>
  <button type="button" class="close" data-dismiss="alert">&times;</button>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>IllustTube</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width,initial-scale=1"> <!-- 画面サイズに表示を調整 -->
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome-animation/0.2.1/font-awesome-animation.css"
    type="text/css" media="all" />
  <%= yield :css %>
</head>

<body>
  <% if not current_page?(root_path) || current_page?(new_user_registration_path) %>
  <header id="grid-header">
    <div class="shadow-sm p-3 mb-3 bg-white rounded">
      <nav class="navbar navbar-expand-lg">
        <%= link_to posts_path do %>
        <%= image_tag("/illusttube.png", class:"title_image") %>
        <% end %>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
            <!-- ログインしている場合 -->
            <%# PC & タブレット用 %>
            <li>
              <%= link_to user_path(current_user.id), class: 'nav-link nav-item underscore', method: :get do %>
              <i class="fa fa-user-plus"></i> マイページ
              <% end %>
            </li>
            <li>
              <%= link_to users_path, class: 'nav-link nav-item underscore', method: :get do %>
              <i class="fas fa-users"></i> ユーザー一覧
              <% end %>
            </li>
            <li>
              <%= link_to new_post_path, class: 'nav-link nav-item underscore', method: :get do %>
              <i class="fas fa-clipboard"></i> 新規投稿
              <% end %>
            </li>

            <li>
              <%= link_to youtube_search_path(keyword: "イラスト 描き方") , class: 'nav-link nav-item underscore', method: :get do %>
              <i class="fab fa-youtube"></i> 動画を検索して新規投稿
              <% end %>
            </li>

            <div class="spview">
              <%# タブレット用 %>
              <hr>

              <center>
                <div>
                  <%= render "shared/profile" %>
                  <%= render "shared/circle" %>
                </div>

                <li>

                  <%= link_to destroy_user_session_path, class: 'btn btn-secondary margin_up', method: :delete do %>
                  <i class="fas fa-sign-out-alt"></i> ログアウト
                  <% end %>

                  <hr>
                  <%= form_tag(search_path, method: 'get', id: "search_form_sp") do %>
                  <%= text_field_tag :search, '',value: params[:search], placeholder: "投稿記事を探す", class: 'search_text_sp search_text' %>
                  <%= button_tag :name => nil, class: "btn-outline-info badge-light search_right_text" do %>
                  <i class="fa fa-search"></i>
                  <% end %>
                  <% end %>
              </center>
              <hr>

              <div class="nav-item underscore">
                <a class="js-modal-open nav-link" href=""><i class="fas fa-envelope"></i> お問い合わせ</a>
              </div>
              <center>
                <footer>
                  &copy;Teppei Mimachi 2021
                </footer>
              </center>
              <div class="modal js-modal">
                <div class="modal__bg js-modal-close"></div>
                <div class="modal__content">
                  <%= render "inquiry/index" %>
                  <a class="js-modal-close" href="">閉じる</a>
                </div>

                <%= render "shared/categories_etc" %>

                <footer>
                  &copy;Teppei Mimachi 2021
                </footer>
              </div>
              <% else %>
              <!-- ログアウトしている場合 -->
              <li>
                <%= link_to root_path, class: 'nav-link nav-item underscore', method: :get do %>
                <i class="fas fa-sign-in-alt"></i> ユーザー登録
                <% end %>
              </li>
              <li>
                <%= link_to new_user_session_path, class: 'nav-link nav-item underscore', method: :get do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
              <div class="spview">
                <hr>
                <center>
                  <%= render "shared/profile" %>
                </center>
                <hr>
                <%= render "shared/inquiry" %>
              </div>
              <% end %>
          </ul>

          <div class="fixed pcview z-index">
            <%# 右に表示 %>
            <%= render "shared/inquiry" %>
          </div>
        </div>
      </nav>
    </div>
  </header>
  <% end %>

  <aside class="px-3">

    <div class="fixed pcview">
      <% unless current_page?(root_path) %>
      <center>
        <div>
          <hr>
          <%= render "shared/profile" %>
          <% end %>
          <% if user_signed_in? %>
          <%# PC用 %>
          <%= render "shared/circle" %>
        </div>
        <div>
          <%= link_to destroy_user_session_path, class: 'btn btn-outline-dark margin_up', method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>ログアウト
          <% end %>
        </div>

        <hr>
        <%= form_tag(search_path, method: 'get', id: "search_form_pc_side") do %>
        <%= text_field_tag :search, '',value: params[:search], placeholder: "投稿記事を探す", class: 'search_text_pc_side search_text' %>
        <%= button_tag :name => nil, class: "btn-outline-info badge-light search_right_text" do %>
        <i class="fa fa-search"></i>
        <% end %>
        <% end %>
      </center>

      <%= render "shared/categories_etc" %>
      <% end %>

      <% unless current_page?(root_path) %>
      <footer>
        &copy;Teppei Mimachi 2021
      </footer>
      <% end %>
    </div>
  </aside>

  <main class="shadow-none p-3 mb-5 bg-white rounded">
    <% unless current_page?(root_path) %>
    <%= render 'layouts/alert' %>
    <% end %>
    <%= yield %>
    <div id="page_top"><a href="#"></a></div>
  </main>

  <%# ローディングの表示 %>
  <% if Rails.env.production? || Rails.env.development? %>
  <div class="loader-wrap">
    <div class="loader">Loading...</div>
  </div>
  <% end %>
</body>

</html>